### ISSUE TITLE
Problem with ">lake build bin"

### ISSUE THREAD

**Issue by adolfont** [siddhartha-gadgil/Saturn#4]
Hi, I tried running

> lake build bin

and the result was:

> error: unknown target `bin`

Could you help me?

**Comment by adolfont** [comment]
I am using:

$ lean --version
Lean (version 4.0.0, commit ec941735c80d, Release)

$ lake --version
Lake version 5.0.0-ec94173 (Lean version 4.0.0)

**Comment by siddhartha-gadgil** [comment]
Just saw this.
Use `lake build nqueens` as there is no executable called `bin`.

**Comment by adolfont** [comment]
It worked! Thanks!

![image](https://github.com/siddhartha-gadgil/Saturn/assets/79562/c411f9ed-65cf-47dc-b5aa-753310156283)
![image](https://github.com/siddhartha-gadgil/Saturn/assets/79562/3dd0a5a8-a363-43f5-a45c-232fdfe67c16)
